[package]
name = "jitdumpdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scroll = { version = "0.11.0", features = ["derive"] }
num_enum = "0.5.9"